### ISSUE TITLE
关于测试部分代码的请求

### ISSUE THREAD

**Issue by Cbiubiu** [RaccoonDML/CHSNet#1]
您好！我对您的研究工作非常感兴趣，特别是关于测试部分的内容。我想了解是否有可能获取测试代码的访问权限。如果您愿意分享测试代码，我将不胜感激。您可以选择将代码公开或者以私信方式发送给我（我的电子邮箱地址是834719293@qq.com）。

        期待着您的回复。

**Comment by RaccoonDML** [comment]
测试部分代码见utils/chsnet_trainer.py的val_epoch。
也可以先将utils/chsnet_trainer.py中第90行的注释掉的`self.val_epoch()`取消注释，然后运行
`python train.py --resume /path/to/pretrained_model --max_epoch 0`
其中`/path/to/pretrained_model`是预训练模型的路径

**Comment by Cbiubiu** [comment]
> 测试部分代码见utils/chsnet_trainer.py的val_epoch。 也可以先将utils/chsnet_trainer.py中第90行的注释掉的`self.val_epoch()`取消注释，然后运行 `python train.py --resume /path/to/pretrained_model --max_epoch 0` 其中`/path/to/pretrained_model`是预训练模型的路径

好的，非常感谢！
